/*--------------------------------------------------------------------
 *
 *
 *  Copyright (c) 1991-2018 by P. Wessel, W. H. F. Smith, R. Scharroo,
 *  F. Wobbe, and J. Luis
 *  See LICENSE.TXT file for copying and redistribution conditions.
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation; version 3 or any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  Contact info: gmt.soest.hawaii.edu
 *--------------------------------------------------------------------
 *
 *  grdmath_op.h is automatically generated by CMake. Do NOT edit manually!
 */

/* Declare operator array */

static char *operator[GRDMATH_N_OPERATORS + 1] = {

	"ABS",	/* id = 0 */
	"ACOS",	/* id = 1 */
	"ACOSH",	/* id = 2 */
	"ACOT",	/* id = 3 */
	"ACOTH",	/* id = 4 */
	"ACSC",	/* id = 5 */
	"ACSCH",	/* id = 6 */
	"ADD",	/* id = 7 */
	"AND",	/* id = 8 */
	"ARC",	/* id = 9 */
	"AREA",	/* id = 10 */
	"ASEC",	/* id = 11 */
	"ASECH",	/* id = 12 */
	"ASIN",	/* id = 13 */
	"ASINH",	/* id = 14 */
	"ATAN",	/* id = 15 */
	"ATAN2",	/* id = 16 */
	"ATANH",	/* id = 17 */
	"BCDF",	/* id = 18 */
	"BPDF",	/* id = 19 */
	"BEI",	/* id = 20 */
	"BER",	/* id = 21 */
	"BITAND",	/* id = 22 */
	"BITLEFT",	/* id = 23 */
	"BITNOT",	/* id = 24 */
	"BITOR",	/* id = 25 */
	"BITRIGHT",	/* id = 26 */
	"BITTEST",	/* id = 27 */
	"BITXOR",	/* id = 28 */
	"CAZ",	/* id = 29 */
	"CBAZ",	/* id = 30 */
	"CDIST",	/* id = 31 */
	"CDIST2",	/* id = 32 */
	"CEIL",	/* id = 33 */
	"CHI2CRIT",	/* id = 34 */
	"CHI2CDF",	/* id = 35 */
	"CHI2PDF",	/* id = 36 */
	"COMB",	/* id = 37 */
	"CORRCOEFF",	/* id = 38 */
	"COS",	/* id = 39 */
	"COSD",	/* id = 40 */
	"COSH",	/* id = 41 */
	"COT",	/* id = 42 */
	"COTD",	/* id = 43 */
	"COTH",	/* id = 44 */
	"PCDF",	/* id = 45 */
	"PPDF",	/* id = 46 */
	"CSC",	/* id = 47 */
	"CSCD",	/* id = 48 */
	"CSCH",	/* id = 49 */
	"CURV",	/* id = 50 */
	"D2DX2",	/* id = 51 */
	"D2DY2",	/* id = 52 */
	"D2DXY",	/* id = 53 */
	"D2R",	/* id = 54 */
	"DDX",	/* id = 55 */
	"DDY",	/* id = 56 */
	"DEG2KM",	/* id = 57 */
	"DENAN",	/* id = 58 */
	"DILOG",	/* id = 59 */
	"DIV",	/* id = 60 */
	"DUP",	/* id = 61 */
	"ECDF",	/* id = 62 */
	"ECRIT",	/* id = 63 */
	"EPDF",	/* id = 64 */
	"ERF",	/* id = 65 */
	"ERFC",	/* id = 66 */
	"EQ",	/* id = 67 */
	"ERFINV",	/* id = 68 */
	"EXCH",	/* id = 69 */
	"EXP",	/* id = 70 */
	"FACT",	/* id = 71 */
	"EXTREMA",	/* id = 72 */
	"FCRIT",	/* id = 73 */
	"FCDF",	/* id = 74 */
	"FLIPLR",	/* id = 75 */
	"FLIPUD",	/* id = 76 */
	"FLOOR",	/* id = 77 */
	"FMOD",	/* id = 78 */
	"FPDF",	/* id = 79 */
	"GE",	/* id = 80 */
	"GT",	/* id = 81 */
	"HYPOT",	/* id = 82 */
	"I0",	/* id = 83 */
	"I1",	/* id = 84 */
	"IFELSE",	/* id = 85 */
	"IN",	/* id = 86 */
	"INRANGE",	/* id = 87 */
	"INSIDE",	/* id = 88 */
	"INV",	/* id = 89 */
	"ISFINITE",	/* id = 90 */
	"ISNAN",	/* id = 91 */
	"J0",	/* id = 92 */
	"J1",	/* id = 93 */
	"JN",	/* id = 94 */
	"K0",	/* id = 95 */
	"K1",	/* id = 96 */
	"KEI",	/* id = 97 */
	"KER",	/* id = 98 */
	"KM2DEG",	/* id = 99 */
	"KN",	/* id = 100 */
	"KURT",	/* id = 101 */
	"LCDF",	/* id = 102 */
	"LCRIT",	/* id = 103 */
	"LDIST",	/* id = 104 */
	"LDISTG",	/* id = 105 */
	"LDIST2",	/* id = 106 */
	"LE",	/* id = 107 */
	"LOG",	/* id = 108 */
	"LOG10",	/* id = 109 */
	"LOG1P",	/* id = 110 */
	"LOG2",	/* id = 111 */
	"LMSSCL",	/* id = 112 */
	"LMSSCLW",	/* id = 113 */
	"LOWER",	/* id = 114 */
	"LPDF",	/* id = 115 */
	"LRAND",	/* id = 116 */
	"LT",	/* id = 117 */
	"MAD",	/* id = 118 */
	"MADW",	/* id = 119 */
	"MAX",	/* id = 120 */
	"MEAN",	/* id = 121 */
	"MEANW",	/* id = 122 */
	"MEDIAN",	/* id = 123 */
	"MEDIANW",	/* id = 124 */
	"MIN",	/* id = 125 */
	"MOD",	/* id = 126 */
	"MODE",	/* id = 127 */
	"MODEW",	/* id = 128 */
	"MUL",	/* id = 129 */
	"NAN",	/* id = 130 */
	"NEG",	/* id = 131 */
	"NEQ",	/* id = 132 */
	"NORM",	/* id = 133 */
	"NOT",	/* id = 134 */
	"NRAND",	/* id = 135 */
	"OR",	/* id = 136 */
	"PDIST",	/* id = 137 */
	"PDIST2",	/* id = 138 */
	"PERM",	/* id = 139 */
	"POP",	/* id = 140 */
	"PLM",	/* id = 141 */
	"PLMg",	/* id = 142 */
	"POINT",	/* id = 143 */
	"POW",	/* id = 144 */
	"PQUANT",	/* id = 145 */
	"PQUANTW",	/* id = 146 */
	"PSI",	/* id = 147 */
	"PV",	/* id = 148 */
	"QV",	/* id = 149 */
	"R2",	/* id = 150 */
	"R2D",	/* id = 151 */
	"RAND",	/* id = 152 */
	"RCDF",	/* id = 153 */
	"RCRIT",	/* id = 154 */
	"RINT",	/* id = 155 */
	"RMS",	/* id = 156 */
	"RMSW",	/* id = 157 */
	"RPDF",	/* id = 158 */
	"ROLL",	/* id = 159 */
	"ROTX",	/* id = 160 */
	"ROTY",	/* id = 161 */
	"SDIST",	/* id = 162 */
	"SDIST2",	/* id = 163 */
	"SAZ",	/* id = 164 */
	"SBAZ",	/* id = 165 */
	"SEC",	/* id = 166 */
	"SECD",	/* id = 167 */
	"SECH",	/* id = 168 */
	"SIGN",	/* id = 169 */
	"SIN",	/* id = 170 */
	"SINC",	/* id = 171 */
	"SIND",	/* id = 172 */
	"SINH",	/* id = 173 */
	"SKEW",	/* id = 174 */
	"SQR",	/* id = 175 */
	"SQRT",	/* id = 176 */
	"STD",	/* id = 177 */
	"STDW",	/* id = 178 */
	"STEP",	/* id = 179 */
	"STEPX",	/* id = 180 */
	"STEPY",	/* id = 181 */
	"SUB",	/* id = 182 */
	"SUM",	/* id = 183 */
	"TAN",	/* id = 184 */
	"TAND",	/* id = 185 */
	"TANH",	/* id = 186 */
	"TAPER",	/* id = 187 */
	"TN",	/* id = 188 */
	"TCRIT",	/* id = 189 */
	"TCDF",	/* id = 190 */
	"TPDF",	/* id = 191 */
	"TRIM",	/* id = 192 */
	"UPPER",	/* id = 193 */
	"VAR",	/* id = 194 */
	"VARW",	/* id = 195 */
	"WCDF",	/* id = 196 */
	"WCRIT",	/* id = 197 */
	"WPDF",	/* id = 198 */
	"WRAP",	/* id = 199 */
	"XOR",	/* id = 200 */
	"Y0",	/* id = 201 */
	"Y1",	/* id = 202 */
	"YLM",	/* id = 203 */
	"YLMg",	/* id = 204 */
	"YN",	/* id = 205 */
	"ZCRIT",	/* id = 206 */
	"ZCDF",	/* id = 207 */
	"ZPDF",	/* id = 208 */
	"" /* last element is intentionally left blank */

};

/* vim: set ft=c: */
