# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ALL_INSTALL_TYPES "Full;Minimal")
set(CPACK_ARCHIVE_COMPONENT_INSTALL "ON")
set(CPACK_BINARY_7Z "")
set(CPACK_BINARY_BUNDLE "")
set(CPACK_BINARY_CYGWIN "")
set(CPACK_BINARY_DEB "")
set(CPACK_BINARY_DRAGNDROP "")
set(CPACK_BINARY_FREEBSD "")
set(CPACK_BINARY_IFW "")
set(CPACK_BINARY_NSIS "")
set(CPACK_BINARY_NUGET "")
set(CPACK_BINARY_OSXX11 "")
set(CPACK_BINARY_PACKAGEMAKER "")
set(CPACK_BINARY_PRODUCTBUILD "")
set(CPACK_BINARY_RPM "")
set(CPACK_BINARY_STGZ "")
set(CPACK_BINARY_TBZ2 "")
set(CPACK_BINARY_TGZ "")
set(CPACK_BINARY_TXZ "")
set(CPACK_BINARY_TZ "")
set(CPACK_BINARY_WIX "")
set(CPACK_BINARY_ZIP "")
set(CPACK_BUILD_SOURCE_DIRS "/MyData/Research/3-CodeProject/ModernGMT/gmt;/MyData/Research/3-CodeProject/ModernGMT/gmt/build")
set(CPACK_BUNDLE_ICON "/MyData/Research/3-CodeProject/ModernGMT/gmt/cmake/dist/GMT.icns")
set(CPACK_BUNDLE_NAME "GMT-6.0.0_c4437e4-dirty")
set(CPACK_BUNDLE_PLIST "/MyData/Research/3-CodeProject/ModernGMT/gmt/build/cmake/dist/Info.plist")
set(CPACK_BUNDLE_STARTUP_COMMAND "/MyData/Research/3-CodeProject/ModernGMT/gmt/build/cmake/dist/startup_macosx.sh")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "Runtime;Documentation;DCW;GSHHG")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENTS_GROUPING "IGNORE")
set(CPACK_COMPONENT_DCW_DESCRIPTION "Digital Chart of the World files.")
set(CPACK_COMPONENT_DOCUMENTATION_DESCRIPTION "Documentation and example files.")
set(CPACK_COMPONENT_DOCUMENTATION_INSTALL_TYPES "Full")
set(CPACK_COMPONENT_GSHHG_DESCRIPTION "Shoreline database files.")
set(CPACK_COMPONENT_GSHHG_INSTALL_TYPES "Full")
set(CPACK_COMPONENT_RUNTIME_DESCRIPTION "GMT programs, libraries and shared files.")
set(CPACK_COMPONENT_RUNTIME_DISPLAY_NAME "Runtime files")
set(CPACK_COMPONENT_RUNTIME_INSTALL_TYPES "Minimal;Full")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "GMT Team <gmt-help@lists.hawaii.edu>")
set(CPACK_DEBIAN_PACKAGE_SECTION "science")
set(CPACK_GENERATOR "Bundle;TGZ;TBZ2")
set(CPACK_INSTALL_CMAKE_PROJECTS "/MyData/Research/3-CodeProject/ModernGMT/gmt/build;GMT;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_INSTALL_TYPE_FULL_DISPLAY_NAME "Everything")
set(CPACK_MODULE_PATH "/MyData/Research/3-CodeProject/ModernGMT/gmt/cmake/modules/")
set(CPACK_NSIS_DISPLAY_NAME "GMT-6.0.0_c4437e4-dirty")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "GMT-6.0.0_c4437e4-dirty")
set(CPACK_OSX_SYSROOT "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk")
set(CPACK_OUTPUT_CONFIG_FILE "/MyData/Research/3-CodeProject/ModernGMT/gmt/build/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/MyData/Research/3-CodeProject/ModernGMT/gmt/cmake/dist/cpack_package_description.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "The Generic Mapping Tools data processing and display software package")
set(CPACK_PACKAGE_FILE_NAME "GMT-6.0.0_c4437e4-dirty-Darwin")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "GMT-6.0.0_c4437e4-dirty")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "GMT-6.0.0_c4437e4-dirty")
set(CPACK_PACKAGE_NAME "GMT")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "The GMT Team")
set(CPACK_PACKAGE_VERSION "6.0.0_c4437e4-dirty")
set(CPACK_PACKAGE_VERSION_MAJOR "6")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_RESOURCE_FILE_LICENSE "/usr/local/Cellar/cmake/3.14.3/share/cmake/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/usr/local/Cellar/cmake/3.14.3/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/local/Cellar/cmake/3.14.3/share/cmake/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_COMPONENT_INSTALL "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "")
set(CPACK_SOURCE_CYGWIN "")
set(CPACK_SOURCE_GENERATOR "TGZ;TBZ2;ZIP")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/MyData/Research/3-CodeProject/ModernGMT/gmt/build/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "")
set(CPACK_SOURCE_TBZ2 "")
set(CPACK_SOURCE_TGZ "")
set(CPACK_SOURCE_TXZ "")
set(CPACK_SOURCE_TZ "")
set(CPACK_SOURCE_ZIP "")
set(CPACK_SYSTEM_NAME "Darwin")
set(CPACK_TOPLEVEL_TAG "Darwin")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/MyData/Research/3-CodeProject/ModernGMT/gmt/build/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
